### ISSUE TITLE
where am I wrong when using equation environment

### ISSUE THREAD

**Issue by JeT76-ESCP** [fangyi-zhou/at-end-of-env#1]
Following this [TeX.SE question](https://tex.stackexchange.com/q/636552/163874), it was a good occasion to try your package !

However, when I simply try to apply it to equation environement, I get an error.

```
\documentclass{article}
\usepackage{atendofenv}

\begin{document}

 \begin{equation}
 G(s) = {X(s) \over U(s)} = {5 \over s^2 + 2 s + 3}
 \end{equation}

\AtEndOfEnv{equation}{$\square$}

\end{document}
```

**Comment by fangyi-zhou** [comment]
Hi, it looks like you didn't include `amssymb` for the `\square` command.

```tex
\documentclass{article}
\usepackage{atendofenv}
\usepackage{amssymb}
\AtEndOfEnv{equation}{$\square$}

\begin{document}

 \begin{equation}
 G(s) = {X(s) \over U(s)} = {5 \over s^2 + 2 s + 3}
 \end{equation}

\end{document}
```

![image](https://user-images.githubusercontent.com/7815439/157778459-d9d348c1-4f6a-48da-b43f-00d4a58568ed.png)


Please reopen this issue if there are other errors.

**Comment by JeT76-ESCP** [comment]
thank you for your answer !
now when i try with `equation*` env I get an error.

```
\documentclass{article}
\usepackage{atendofenv}
\usepackage{amssymb}
\AtEndOfEnv{equation*}{$\square$}

\begin{document}

 \begin{equation*}
 G(s) = {X(s) \over U(s)} = {5 \over s^2 + 2 s + 3}
 \end{equation*}

\end{document}
```

**Comment by fangyi-zhou** [comment]
You forgot to include `amsmath` package, which provides the `equation*` environement
